/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kankan_player_util_CidUtil */

#ifndef _Included_com_kankan_player_util_CidUtil
#define _Included_com_kankan_player_util_CidUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_kankan_player_util_CidUtil_CID_PART_SIZE
#define com_kankan_player_util_CidUtil_CID_PART_SIZE 20480L
/*
 * Class:     com_kankan_player_util_CidUtil
 * Method:    nativeQueryCidByPath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kankan_player_util_CidUtil_nativeQueryCidByPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_kankan_player_util_CidUtil
 * Method:    nativeQueryCidByData
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kankan_player_util_CidUtil_nativeQueryCidByData
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
