package com.kankan.player.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SUBTITLE.
 */
public class Subtitle implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String cid;
    private String name;
    private String language;
    private Integer rate;
    private String display;
    private String downloadurl;
    private String localpath;
    private Integer svote;
    private Long offset;
    private Integer type;
    private Boolean selected;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Subtitle() {
    }

    public Subtitle(Long id) {
        this.id = id;
    }

    public Subtitle(Long id, String cid, String name, String language, Integer rate, String display, String downloadurl, String localpath, Integer svote, Long offset, Integer type, Boolean selected) {
        this.id = id;
        this.cid = cid;
        this.name = name;
        this.language = language;
        this.rate = rate;
        this.display = display;
        this.downloadurl = downloadurl;
        this.localpath = localpath;
        this.svote = svote;
        this.offset = offset;
        this.type = type;
        this.selected = selected;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCid() {
        return cid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public Integer getRate() {
        return rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

    public String getDisplay() {
        return display;
    }

    public void setDisplay(String display) {
        this.display = display;
    }

    public String getDownloadurl() {
        return downloadurl;
    }

    public void setDownloadurl(String downloadurl) {
        this.downloadurl = downloadurl;
    }

    public String getLocalpath() {
        return localpath;
    }

    public void setLocalpath(String localpath) {
        this.localpath = localpath;
    }

    public Integer getSvote() {
        return svote;
    }

    public void setSvote(Integer svote) {
        this.svote = svote;
    }

    public Long getOffset() {
        return offset;
    }

    public void setOffset(Long offset) {
        this.offset = offset;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Boolean getSelected() {
        return selected;
    }

    public void setSelected(Boolean selected) {
        this.selected = selected;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
