package com.kankan.player.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TDVIDEO.
 */
public class TDVideo {

    private Long id;
    private String cid;
    /** Not-null value. */
    private String filePath;
    private String fileName;
    private Long fileSize;
    private Long createTime;
    private Integer fileType;
    private Boolean islooked;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TDVideo() {
    }

    public TDVideo(Long id) {
        this.id = id;
    }

    public TDVideo(Long id, String cid, String filePath, String fileName, Long fileSize, Long createTime, Integer fileType, Boolean islooked) {
        this.id = id;
        this.cid = cid;
        this.filePath = filePath;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.createTime = createTime;
        this.fileType = fileType;
        this.islooked = islooked;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCid() {
        return cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    /** Not-null value. */
    public String getFilePath() {
        return filePath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Integer getFileType() {
        return fileType;
    }

    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    public Boolean getIslooked() {
        return islooked;
    }

    public void setIslooked(Boolean islooked) {
        this.islooked = islooked;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
