package com.kankan.player.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table VIDEO_HISTORY.
 */
public class VideoHistory {

    private Long id;
    /** Not-null value. */
    private String cid;
    /** Not-null value. */
    private String filePath;
    private String fileName;
    private String subtitlePath;
    private Integer width;
    private Integer height;
    private Integer duration;
    private Integer progress;
    private String thumbnailPath;
    private long timestamp;
    private String deviceName;
    private Integer deviceType;
    private Integer displayMode;
    private Integer audioMode;
    private Integer subtitleType;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public VideoHistory() {
    }

    public VideoHistory(Long id) {
        this.id = id;
    }

    public VideoHistory(Long id, String cid, String filePath, String fileName, String subtitlePath, Integer width, Integer height, Integer duration, Integer progress, String thumbnailPath, long timestamp, String deviceName, Integer deviceType, Integer displayMode, Integer audioMode, Integer subtitleType) {
        this.id = id;
        this.cid = cid;
        this.filePath = filePath;
        this.fileName = fileName;
        this.subtitlePath = subtitlePath;
        this.width = width;
        this.height = height;
        this.duration = duration;
        this.progress = progress;
        this.thumbnailPath = thumbnailPath;
        this.timestamp = timestamp;
        this.deviceName = deviceName;
        this.deviceType = deviceType;
        this.displayMode = displayMode;
        this.audioMode = audioMode;
        this.subtitleType = subtitleType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCid() {
        return cid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /** Not-null value. */
    public String getFilePath() {
        return filePath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getSubtitlePath() {
        return subtitlePath;
    }

    public void setSubtitlePath(String subtitlePath) {
        this.subtitlePath = subtitlePath;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    public String getThumbnailPath() {
        return thumbnailPath;
    }

    public void setThumbnailPath(String thumbnailPath) {
        this.thumbnailPath = thumbnailPath;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public String getDeviceName() {
        return deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    public Integer getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    public Integer getDisplayMode() {
        return displayMode;
    }

    public void setDisplayMode(Integer displayMode) {
        this.displayMode = displayMode;
    }

    public Integer getAudioMode() {
        return audioMode;
    }

    public void setAudioMode(Integer audioMode) {
        this.audioMode = audioMode;
    }

    public Integer getSubtitleType() {
        return subtitleType;
    }

    public void setSubtitleType(Integer subtitleType) {
        this.subtitleType = subtitleType;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
